//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

serializers.thrift.media.UploadMedia_Upload_args = function(args) {
  this.media = null;
  if (args) {
    if (args.media !== undefined && args.media !== null) {
      this.media = new serializers.thrift.media.Media(args.media);
    }
  }
};
serializers.thrift.media.UploadMedia_Upload_args.prototype = {};
serializers.thrift.media.UploadMedia_Upload_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.media = new serializers.thrift.media.Media();
        this.media.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

serializers.thrift.media.UploadMedia_Upload_args.prototype.write = function(output) {
  output.writeStructBegin('UploadMedia_Upload_args');
  if (this.media !== null && this.media !== undefined) {
    output.writeFieldBegin('media', Thrift.Type.STRUCT, 1);
    this.media.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

serializers.thrift.media.UploadMedia_Upload_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new serializers.thrift.media.Response(args.success);
    }
  }
};
serializers.thrift.media.UploadMedia_Upload_result.prototype = {};
serializers.thrift.media.UploadMedia_Upload_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new serializers.thrift.media.Response();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

serializers.thrift.media.UploadMedia_Upload_result.prototype.write = function(output) {
  output.writeStructBegin('UploadMedia_Upload_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

serializers.thrift.media.UploadMediaClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
serializers.thrift.media.UploadMediaClient.prototype = {};
serializers.thrift.media.UploadMediaClient.prototype.Upload = function(media, callback) {
  this.send_Upload(media, callback); 
  if (!callback) {
    return this.recv_Upload();
  }
};

serializers.thrift.media.UploadMediaClient.prototype.send_Upload = function(media, callback) {
  var params = {
    media: media
  };
  var args = new serializers.thrift.media.UploadMedia_Upload_args(params);
  try {
    this.output.writeMessageBegin('Upload', Thrift.MessageType.CALL, this.seqid);
    args.write(this.output);
    this.output.writeMessageEnd();
    if (callback) {
      var self = this;
      this.output.getTransport().flush(true, function() {
        var result = null;
        try {
          result = self.recv_Upload();
        } catch (e) {
          result = e;
        }
        callback(result);
      });
    } else {
      return this.output.getTransport().flush();
    }
  }
  catch (e) {
    if (typeof this.output.getTransport().reset === 'function') {
      this.output.getTransport().reset();
    }
    throw e;
  }
};

serializers.thrift.media.UploadMediaClient.prototype.recv_Upload = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new serializers.thrift.media.UploadMedia_Upload_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'Upload failed: unknown result';
};
