//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./msg_types');
//HELPER FUNCTIONS AND STRUCTURES

var UploadMedia_Upload_args = function(args) {
  this.media = null;
  if (args) {
    if (args.media !== undefined && args.media !== null) {
      this.media = new ttypes.Media(args.media);
    }
  }
};
UploadMedia_Upload_args.prototype = {};
UploadMedia_Upload_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.media = new ttypes.Media();
        this.media.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UploadMedia_Upload_args.prototype.write = function(output) {
  output.writeStructBegin('UploadMedia_Upload_args');
  if (this.media !== null && this.media !== undefined) {
    output.writeFieldBegin('media', Thrift.Type.STRUCT, 1);
    this.media.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UploadMedia_Upload_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.Response(args.success);
    }
  }
};
UploadMedia_Upload_result.prototype = {};
UploadMedia_Upload_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Response();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UploadMedia_Upload_result.prototype.write = function(output) {
  output.writeStructBegin('UploadMedia_Upload_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UploadMediaClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
UploadMediaClient.prototype = {};
UploadMediaClient.prototype.seqid = function() { return this._seqid; };
UploadMediaClient.prototype.new_seqid = function() { return this._seqid += 1; };
UploadMediaClient.prototype.Upload = function(media, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_Upload(media);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_Upload(media);
  }
};

UploadMediaClient.prototype.send_Upload = function(media) {
  var output = new this.pClass(this.output);
  var params = {
    media: media
  };
  var args = new UploadMedia_Upload_args(params);
  try {
    output.writeMessageBegin('Upload', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

UploadMediaClient.prototype.recv_Upload = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new UploadMedia_Upload_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('Upload failed: unknown result');
};
var UploadMediaProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
UploadMediaProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
UploadMediaProcessor.prototype.process_Upload = function(seqid, input, output) {
  var args = new UploadMedia_Upload_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.Upload.length === 1) {
    Q.fcall(this._handler.Upload.bind(this._handler), args.media)
      .then(function(result) {
        var result_obj = new UploadMedia_Upload_result({success: result});
        output.writeMessageBegin("Upload", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("Upload", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.Upload(args.media, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new UploadMedia_Upload_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("Upload", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("Upload", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
